app_recipe/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import (
    RegisterUser,
    index,
    UserLogin,
    AddRecipe,
    viewRecipe,
    updateRecipe,
    RecipeDeleteView,
    userDetails,
    createReport,
    reviews,
    all_recipes,
    logoutV,
)
app_name = 'app_recipe'
urlpatterns = [
    path('',index, name = 'index_page'),
    path('login/', UserLogin.as_view(), name = "login_view"),
    path('register/', RegisterUser, name = 'user_registration' ),
    path('add/', AddRecipe, name = 'add_recipe'),
    path('view/<int:id>/', viewRecipe, name = 'view_recipe'),
    path('view/<int:id>/update/', updateRecipe, name = 'update_recipe'),
    path('view/<pk>/delete/', RecipeDeleteView.as_view(), name = 'delete_recipe'),
    path('user/<int:id>', userDetails, name = 'user_data'),
    path('view/<pk>/report', createReport, name = 'create_report'),
    path('reviews/', reviews, name = 'reviews'),
    path('view/', all_recipes,name = 'all_recipes'),
    path('logout/',logoutV, name = 'logout_view'),

]

cuser/urls.py
from django.urls import path
# from .views import verify_user, RegisterUser, CreateUser, UserLogin

# app_name = 'cuser'

# urlpatterns = [
#     path('', verify_user, name = 'verify'),
#     path('from/', RegisterUser.as_view(), name = 'register'),
#     path('create/', CreateUser),
#     path('login/', UserLogin.as_view(), name = 'login_user')

# ]

recipe_ms/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', include('cuser.urls')),
    path('',include('app_recipe.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

app_recipe/models.py
# import cuser
from cuser.models import CustomUser
from django.db import models
from django.shortcuts import reverse
# Create your models here.

class UserInfo(models.Model):
    """ The model is OneToOne extension of the UserAdmin
    with extended fields firstName LastName & address """
    user        = models.OneToOneField(CustomUser,
                on_delete = models.CASCADE,
                null = True,
                blank = True,
                )

    firstName   = models.CharField(max_length = 30, null= True, blank= True)
    lastName    = models.CharField(max_length = 30, null= True, blank= True)
    address     = models.CharField(max_length = 30, null= True, blank = True)

    profile     = models.ImageField(upload_to = 'profile/',
                    blank = True, null = True,
                    default = 'profile_default.png')
    def __str__(self):
        return f'{ self.firstName } {self.lastName}'

class Category(models.Model):
    """ This stores the data required to define category of Recipe """
    c_type      = models.CharField(max_length= 30)
    region      = models.CharField(max_length=30)
    is_veg      = models.BooleanField(blank= False, null= False)

    def __str__(self):
        return f'{ self.c_type }'

class Recipe(models.Model):
    """ The model consists of all the information about Recipes"""
    recipe_name     = models.CharField(max_length= 100, blank = False, null= False)
    description     = models.TextField(blank= False, null= False)
    quantity        = models.CharField(max_length= 30, null=True, blank= True)
    date_added      = models.DateTimeField(auto_now_add= True, blank= False)
    recipe_type     = models.ForeignKey(Category,
                            blank= True, null= True,
                            on_delete = models.CASCADE
                            )
    created_by      = models.ForeignKey(
                    CustomUser,
                    on_delete=models.CASCADE
        )
    image_file      = models.ImageField(null = True, blank = True,default = 'image_default.png')
    def __str__(self):
        return f'{ self.recipe_name }'



# The models to be made after recipe

class Comment(models.Model):
    """ The model consists of comments made by user in Recipes """
    description     = models.CharField(max_length = 255, null = False, blank = False)
    recipe          = models.ForeignKey(Recipe, on_delete = models.CASCADE, null= True, blank= True)
    created_by      = models.ForeignKey(CustomUser, on_delete= models.CASCADE, null= True, blank= True)
    is_appropriate  = models.BooleanField(default= True)
    def __str__(self):
        return f'Id: {self.description}'


class Report(models.Model):
    """ The model consists of Reports to the Recipes """
    title           = models.CharField(max_length= 30, blank= False, null= False)
    description     = models.CharField(max_length = 255, null = False, blank = False)
    recipe          = models.ForeignKey(Recipe, on_delete = models.CASCADE, null= True, blank= True)
    created_by      = models.ForeignKey(CustomUser, on_delete= models.CASCADE, null= True, blank= True)
    is_repeated     = models.BooleanField(default= False)

    def __str__(self):
        return f'{ self.title }'

class Ingredient(models.Model):
    """ This model containsinfo about ingredients """
    ingredient_name     = models.CharField(max_length=100, unique= True)
    ingredient_type     = models.CharField(max_length=30)
    measurement_scale   = models.CharField(max_length=30)
    
    def __str__(self):
        return f'{ self.ingredient_name }'

class Recipe_Ingredient(models.Model):
    recipe      = models.ForeignKey(Recipe,
                    blank= True, null= False,
                    on_delete = models.CASCADE)
    ingredient  = models.ForeignKey(Ingredient,
                    blank = False, null= False,
                    on_delete = models.CASCADE)
    amount      = models.FloatField(null=False, blank= False)

    def __str__(self):
        return f'{self.ingredient}'

app_recipe/forms.py
from django import forms
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from .models import ( 
    UserInfo,
    Category, 
    Recipe,
    Comment,
    Report,
    Recipe_Ingredient,
)
from cuser.models import CustomUser

class UserForm(forms.ModelForm):
    class Meta:
        model = UserInfo
        exclude = ('user',)


class RecipeForm(forms.ModelForm):
    class Meta:
        model   = Recipe
        fields  = ('recipe_name', 'description', 'quantity', 'recipe_type', 'image_file')

class RIForm(forms.ModelForm):
    class Meta:
        model   = Recipe_Ingredient
        exclude = ('recipe',)

class CommentForm(forms.ModelForm):
    class Meta:
        model   = Comment
        exclude = ('recipe', 'created_by', 'is_appropriate',)

class ReportForm(forms.ModelForm):
    class Meta:
        model   = Report
        exclude = ('recipe', 'created_by','is_repeated')

app_recipe/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import (
    render,
    redirect,
    reverse,
    get_object_or_404,
    HttpResponseRedirect
)
from cuser.forms import RegisterForm
from django.forms import inlineformset_factory
from .forms import (
    UserForm,
    RecipeForm,
    RIForm,
    CommentForm,
    ReportForm,
)
from django.contrib.auth.views import LoginView 
from django.views.generic import DeleteView
from django.http import Http404
from django.contrib.auth import authenticate, login, logout
from .models import ( 
    UserInfo,
    Category, 
    Recipe,
    Comment,
    Report,
    Recipe_Ingredient,
    CustomUser
)
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.

def index(request):
    user = get_object_or_404(CustomUser,id = 2)
    # last_ten = Messages.objects.filter(since=since).order_by('-id')[:10]
    recipe = Recipe.objects.filter(created_by= user)
    print(request.user, recipe)
    """ The function to render homepage of the app """
    return render(request, 'app_recipe/cookit1.html', {'recipes' : recipe})

def all_recipes(request):
    recipe = Recipe.objects.all()
    return render(request,'app_recipe/all_recipes.html',{ 'recipes': recipe })
def reviews(request):
    return render(request,'app_recipe/reviews.html')

def logoutV(request):
    if request.user:
        logout(request)
        return redirect('/')
    else:
        return redirect(reverse('login_view'))

class UserLogin(LoginView):
    """ The login view for the user """
    template_name = 'app_recipe/login.html'
    # success_url = 'app_recipe:index_page'
    LOGIN_REDIRECT_URL = 'app_recipe:index_page'
    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect(reverse('app_recipe:index_page'))
        return super(UserLogin, self).get(request, *args, **kwargs)

def RegisterUser(request):
    """ User registration """
    if request.method == 'POST':
        reg_form = RegisterForm(request.POST or None)
        user_form = UserForm(request.POST or None)
        if user_form.is_valid() and reg_form.is_valid():
            print(user_form.cleaned_data, reg_form.cleaned_data)
            reg_user    = reg_form.save()
            user_data   = user_form.save(commit= False)
            user_data.user = reg_user
            user_data.save()
            return redirect(reverse('app_recipe:login_view'))
    else:
        reg_form = RegisterForm()
        user_form = UserForm()
    return render(request, 'app_recipe/register.html', {
        'form1' : reg_form,
        'form2' : user_form,
    })

@login_required(login_url = 'app_recipe:login_view')
def AddRecipe(request):
    """ Function to add recipes """
    user    = request.user
    RForm   = RecipeForm(initial = {'created_by' : user})
    RIFForm = inlineformset_factory(Recipe, Recipe_Ingredient, fields= ('ingredient', 'amount'),extra= 5, can_delete= False )
    formset = RIFForm(instance= None)
    if request.method == 'POST':
        RForm   = RecipeForm(request.POST or None, request.FILES)
        if RForm.is_valid():
            recipedata      = RForm.save(commit=False)
            recipedata.created_by = request.user
            recipedata.save()
            # saveFormSet     = formset.save(commit= False)
            formset = RIFForm(request.POST or None, instance= recipedata)
            if formset.is_valid():
                formset.save()
            return redirect(reverse('app_recipe:index_page'))

    return render(request,
     'app_recipe/recipe_add.html',
     {
        'RForm' : RForm,
        'formset' : formset,  
     }
    )


def viewRecipe(request, id):
    commentform = CommentForm()
    recipe      = Recipe.objects.get(id = id)
    comments    = Comment.objects.filter(recipe= recipe)
    ingredients = Recipe_Ingredient.objects.filter(recipe= recipe)
    if not recipe:
        raise Http404
    if request.method == 'POST':
        commentform = CommentForm(request.POST)
        if commentform.is_valid():
            print('it is valid')
            form_save = commentform.save(commit = False)
            form_save.created_by = request.user
            form_save.recipe = recipe
            form_save.save()

    return render(request, 'app_recipe/recipe_details.html',{
        'recipeInfo' : recipe,
        'comments'   : comments,
        'ingredients': ingredients,
        'form'       : commentform,

    })

# @login_required(login_url = 'app_recipe:login_view')
# def viewRecipe(request, id):
#     """ The function to view the info about a certain recipe """
#     recipe      = get_object_or_404(Recipe,id = id )
#     comments    = Comment.objects.filter(recipe = recipe)
#     print(request.user, recipe)
#     ingredients = {}
#     if recipe:
#         if request.method == "POST":
#             recipe      = get_object_or_404(Recipe,id = id )
#             user_obj    = get_object_or_404(CustomUser, id = request.user.id)
#             # comments    = Comment.objects.filter(recipe = recipe)
#             form_r = CommentForm(request.POST or None )
#             if form_r.is_valid():
#                 # user = get_object_or_404(CustomUser)
#                 form_r.save(commit = False)
#                 form_r.created_by = user_obj
#                 # recipe_id = Recipe.objects.get(id = id)
#                 form_r.recipe = recipe
#                 print("Comment before")
#                 form_r.save()
#                 print("Comment")
#         ingredients   = Recipe_Ingredient.objects.filter(recipe = recipe)
#     # print(recipe[0].recipe_name, "and" , ingredients)
#         return render(request, 'app_recipe/recipe_details.html',
#             {
#                 'recipeInfo' : recipe,
#                 'ingredients' : ingredients,
#                 'message'     : None,
#                 'form'        : CommentForm(),
#                 'comments'     : comments
#             }
#         )
#     return render(request, 'app_recipe/recipe_details.html',
#             {
#                 'recipeInfo' : None,
#                 'ingredients' : ingredients,
#                 'form'        : CommentForm(), 
#                 'message'     : "Recipe doesn't exist",
#             })

@login_required(login_url = 'app_recipe:login_view')
def updateRecipe(request,id):
    """ Function to add recipes """
    user    = request.user
    instance= Recipe.objects.get(id = id)
    if user != instance.created_by:
        return redirect(reverse('app_recipe:view_recipe', kwargs={'id' : id}))
    RForm   = RecipeForm(initial = {'created_by' : user}, instance= instance )
    RIFForm = inlineformset_factory(Recipe, Recipe_Ingredient, fields= ('ingredient', 'amount'))
    formset = RIFForm(instance= instance)
    if request.method == 'POST':
        RForm   = RecipeForm(request.POST or None, instance= instance)
        if RForm.is_valid():
            recipedata      = RForm.save(commit=False)
            recipedata.created_by = request.user
            recipedata.save()
            # saveFormSet     = formset.save(commit= False)
            formset = RIFForm(request.POST or None, instance= recipedata)
            if formset.is_valid():
                formset.save()
            return redirect(reverse('app_recipe:index_page'))

    return render(request,
     'app_recipe/recipe_add.html',
     {
        'RForm' : RForm,
        'formset' : formset,  
     }
    )



# class RecipeDeleteView(DeleteView):
#     def get_object(self, queryset=None):
#         """ Hook to ensure object is owned by request.user. """
#         obj = super(RecipeDeleteView, self).get_object()
#         if not obj.created_by == self.request.user:
#             raise Http404
#         return obj

class RecipeDeleteView(LoginRequiredMixin,DeleteView):
    model = Recipe
    template_name = 'app_recipe/delete_recipe.html'
    success_url = '/'
    login_url = '/login/'
    redirect_field_name = 'login_view'

    def get_object(self, queryset=None):
        """ Hook to ensure object is owned by request.user. """
        obj = super(RecipeDeleteView, self).get_object()
        if not obj.created_by == self.request.user:
            return Http404
        return obj

def userDetails(request, id):
    user = get_object_or_404(CustomUser, id = id)
    extra = get_object_or_404(UserInfo,user = user )
    return render(request, 'app_recipe/user_details.html', 
    {'user' : user, 'extra' : extra})

@login_required(login_url = 'app_recipe:login_view')
def createReport(request, pk):
    reportform = ReportForm()
    recipe      = Recipe.objects.get(id = pk)
    # comments    = Comment.objects.filter(recipe= recipe)
    # ingredients = Recipe_Ingredient.objects.filter(recipe= recipe)
    if not recipe:
        raise Http404
    if request.method == 'POST':
        reportform = ReportForm(request.POST)
        if reportform.is_valid():
            print('it is valid')
            form_save = reportform.save(commit = False)
            form_save.created_by = request.user
            form_save.recipe = recipe
            form_save.save()
            return redirect(reverse('app_recipe:all_recipes'))

    return render(request, 'app_recipe/report_recipe.html',{
        # 'recipeInfo' : recipe,
        # 'comments'   : comments,
        # 'ingredients': ingredients,
        'form'       : reportform,

    })

   
   
   
   
   
   
   
   
    # repo = ReportForm()
    # user = request.user
    # recipe_data = Recipe.objects.get(pk = pk)
    # # recipe_data = get_object_or_404(Recipe, id = pk)
    # # try:
    # #     recipe = Recipe.objects.get(id = id)
    # # except recipe.DoesNotExist:
    # #     return render(request,'app_recipe/report_recipe.html', {
    # #         'message'   : 'Recipe does not exist',
    # #         'form'      : repo,
    # #     })
    # if request.method == "POST":
    #     repo = ReportForm(request.POST)

app_recipe/templates/app_recipe/all_recipes.html
{% extends 'app_recipe/base.html' %}
{% load static %}
{% block content %}
<div class="background1">
    <div class="container">
        <div class="popular">
            <h3>Popular recipes collection </h3>
        </div>
        <div class="row">
            {% for recipe in recipes %}
			<div class="col-sm">
				<img class="pho" src="{{ recipe.image_file.url }}">
				<div class="col-sm">
					<div class="colm">
						<a href="{% url 'app_recipe:view_recipe' id=recipe.id  %}"><span>{{ recipe.recipe_name }}</span></a>
					</div>
				</div>
			</div>
			{% endfor %}
        </div>
    </div>
    <div class="container">
        <div class="wrapper">
            <span class="visible">
                <span class="inner">
                    More recipe collections
                </span>
            </span>
        </div>
    </div>
    
</div>

{% endblock %}

app_recipe/templates/app_recipe/base.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>COOKIT</title>
	<link rel="stylesheet" type="text/css" href="{% static 'app_recipe/css/card.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'app_recipe/css/cookit.css' %}">
	<link href="https://fonts.googleapis.com/css?family=Oswald|PT+Sans|Raleway|Staatliches" rel="stylesheet">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css"
		integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
	<!-- CSS only -->
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet"
		integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
</head>

<body>
	<nav id="navbar">
		<div class="container">
			<img id="logo" src="{% static 'app_recipe/images/logo.png' %}">
			<h1 class="logo"> <a href="{% url 'app_recipe:index_page' %}"> COOK IT</a></h1>
			<ul>
				{% if not request.user.is_authenticated %}
				<li><a href="{% url 'app_recipe:login_view' %}" target="f3" class="login"><i class="fas fa-user"></i> </a>
				</li>
				<li><a href="{% url 'app_recipe:login_view' %}" class="login">Sign in </a>
				</li>
				<li>|</li>
				<li><a href="{% url 'app_recipe:user_registration' %}"  class="login">Register</a>
				</li>
				{% else %}
				<li><a href="{% url 'app_recipe:user_data' id=request.user.id %}" target="f3" class="login"><i class="fas fa-user"></i> </a>
				</li>
				<li><a href="{% url 'app_recipe:user_data' id=request.user.id %}" class="login"> {{request.user}} </a>
				</li>
				<li>|</li>
				<li><a href="{% url 'app_recipe:logout_view' %}"  class="login">Logout</a>
				</li>

				{% endif %}

			</ul>
			<div class="search">
				<form>
					<input type="text" placeholder="Search..." />
					<button type="Submit" name="Search" class="button"><i class="fas fa-search"></i> </button>
				</form>
			</div>

		</div>
	</nav>
	{% block content %}
	{% endblock %}

</body>
<footer id="main-footer">
	<div class="appbox">
		<div class="box1">
			<div class="button1">
				<div class="Icon">
					<i class="fab fa-android"></i>
				</div>Get the Android App
			</div>
		</div>
		<div class="button1">
			<div class="Icon">
				<i class="fab fa-apple"></i>
			</div>Get the iOS App
		</div>
	</div>
	<div class="foot-content">
		<span>PRIVICY POLICY</span><span>TERMS AND CONDITIONS</span> <span>CONTACT</span>
	</div>
	<div class="footer-rights">
		<span>COPYRIGHT &copy; 2021 COOKING IT Pvt.Ltd.</span>
	</div>
</footer>


</html>

app_recipe/templates/app_recipe/cookit1.html
{% extends 'app_recipe/base.html' %}
{% load static %}
{% block content %}
<div class="background-col">
    <div class="container">
        <div class="topnav">
            <ul>
                <span>
                    <li><a href="{% url 'app_recipe:all_recipes' %}">Recipes </a></li>
                </span>
                <span>
                    <li> <a href="{% url 'app_recipe:add_recipe' %}">Add Recipes</a></li>
                </span>
                <span>
                    <li> <a href="{% url 'app_recipe:reviews' %}">Reviews </a></li>
                </span>
                <span>
                    <li><a href="#">Contact</a></li>
                </span>
            </ul>
            <div class="line"></div>
        </div>
    </div>
</div>
<div class="showcase">
    </br>
    <h2>
        <span> Welcome to the best website</span></br> <span> to discuss about food </span></br> <span> and
            stuff. </spam></br> </span>
        <span>We are here at your service.</span>
    </h2>
    </br>{% if not request.user.is_authenticated %}
    <a href="{% url 'app_recipe:login_view' %}">
        <div class="join">
            <span class="visible">
                <span class="inner">
                    Join Now
                </span>
            </span>
        </div>
    </a>
    {% endif %}
</div>
<div class="background">
    <div class="container">
        <div class="olive">
            <section id="about-info">
                <div class="info-left">
                    <img src="{% static 'app_recipe/images/olive-oil.jpg' %}" alt="Cookit">
                </div>
                <div class="info-right">
                    <h3>Make recipes your own</h3>
                    <span>With Cookit's recipe editor, you can easily edit recipes, save adjustments to ingredients,
                        and
                        add additional steps or tips to your preparation.</span>
                    <h3>All in one place</h3>
                    <span>
                        Storing your recipes in Cookit allows you to quickly search, find, and select what you want
                        to
                        cook.
                    </span>
                    <h3>Cook from your favorite device</h3>
                    <span>Cookit stores your recipes in the Cloud so you can access them on any device through our
                        website
                        or
                        Android/iOS app.<span>
                </div>
            </section>
        </div>
    </div>
</div>
<div class="background1">
    <div class="container">
        <div class="popular">
            <h3>Popular recipes collection </h3>
        </div>
        <div class="row">
            {% for recipe in recipes %}
			<div class="col-sm">
				<img class="pho" src="{{ recipe.image_file.url }}">
				<div class="col-sm">
					<div class="colm">
						<span>{{ recipe.id }}</span>
					</div>
				</div>
			</div>
			{% endfor %}
        </div>
    </div>
    <div class="container">
        <div class="wrapper">
            <a href="{% url 'app_recipe:all_recipes' %}">
                <span class="inner">
            <span class="visible">
                    More recipe collections
                </span>
            </span>
        </a>
        </div>
    </div>
    <div class="add-import">
        <div class="container">
            <div class="wrapper2">
                <span class="inner">
                    <h3>Add Recipe</h3><span>Import from websites or enter using our side by side recipe form</span>
                </span>
            </div>
        </div>
        <div class="container">
            <div class="addbox">
                <div class="info-left1">
                    <img src="{% static 'app_recipe/images/add1.jpg' %}" alt="add">
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

app_recipe/templates/app_recipe/delete_recipe.html
{% extends 'app_recipe/base.html' %}
{% load static %}
{% block content %}
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object.id }}"?</p>
    <input type="submit" value="Confirm">
</form>
{% if messages %}
    {{ messages }}
{% endif %}


{% endblock %}

app_recipe/templates/app_recipe/login.html
{% extends 'app_recipe/base.html' %}
{% load static %}
{% block content %}

<div class="background-col">
	<div class="row">
		<div class="col-sm">
			<div class="col-sm">
			</div>
		</div>
		<div class="col-sm">
			<div class="background1">
				<div class="container">
					<div class="main">
						<form class="box" method="POST">
							<h1>Login</h1>
							<p class="text-muted"> Please enter your login and password!</p>
							{% csrf_token %}
							{% if message %}
								{{ message }}
							{% endif %}
        					{{ form.as_p }}
							<!-- <a class="forgot text-muted" href="#">Forgot password?</a> -->
							<input class="login" type="submit"  value="Send">
						</form>
					</div>
				</div>
			</div>
			<div class="col-sm">
			</div>
		</div>
		<div class="col-sm">
			<div class="col-sm">
			</div>
		</div>
	</div>
</div>
</div>
</div>

{% endblock %}

app_recipe/templates/app_recipe/recipe_details.html
{% extends 'app_recipe/base.html' %}
{% load static %}
{% block content %}

<div class="container">
    <!-- <div class="welcome">
        <span><a href="cookit.html"> Home</a> >> Welcome to Recipes</span>
    </div> -->
    <div class="wrapper-box">
        <div class="wrapper1">
            <span class="inner">
                {{ recipeInfo.recipe_name }}
            </span>
        </div>
    </div>
</div>
</div>
<div class="background-col1">
<div class="container">
    <div class="recipe-photo">
        <div class="text-center">
            <img src="{{ recipeInfo.image_file.url }}" class="rounded" alt="chicken_pasta">
        </div>
    </div>
</div>
</div>
<div class="background3">
<div class="container">
    <div class="ingredient">
        <span class="inner">
            <h3> Ingredients</h3>
        </span>
        <div class="ingredient-content">
            <span> 
                {% for ri in ingredients %}<br>
                {{ ri.ingredient }} : {{ ri.amount }} {{ ri.ingredient.measurement_scale }} <br>
                    
                {% endfor %}
            </span>
        </div>
    </div>
    <div class="description">
        <span class="inner">
            <h3> Description</h3>
        </span>
        <div class="description-content">
            {{ recipeInfo.description }}
            <p>  </p>
        </div>
    </div>
</div>
</div>
<div class="background-col">
    <div class="whole-box">
        <div class="container">
            {% if request.user == recipeInfo.created_by %}
        <a class="buttn" href="{% url 'app_recipe:update_recipe' id=recipeInfo.id %}">Delete </a><br><br><br>
        <a class="buttn" href="{% url 'app_recipe:update_recipe' id=recipeInfo.id %}">update </a><br><br>
            {% endif %}
        <div class="comment-box">
            <div class="comment">
                <!-- <input type="text" placeholder="Add comment" /> -->
                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.description }}
                    <!-- <input class="bttn" type="submit" value="Comment"> -->
                    <button type="Submit" name="Search" class="buttn">Comment </button>
                    
                </form>
            </div>
        </div>
    </div>
</div>
<br>
<div class="whole-box">
    <div class="container">
        <div class=comments1>
            <div class="head">
                <h3>COMMENTS</h3>
            </div>
            <div class=contents>
                <div class=comment1>
                    <!-- <img src="./images/milan.jpg" alt="milAN"> -->
                </div>
                <div class=user1>
                {% for comment in comments %}
                    {{comment.created_by}} </div>
                <p>{{ comment.description }}</p>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
</div>

    <!-- {% if recipeInfo %}
        
        <div style="background-image: url('{{ recipeInfo.image_file.url }}'); height: 200px;;width: 200px;" alt="photo" srcset="" ><a href="{{ recipeInfo.image_file.url }}">view full image</a></div>
        {{recipeInfo.id}} <br>
        {{ recipeInfo.recipe_name }} <br>
        {{ recipeInfo.description }}<br>
        {{ recipeInfo.quantity }}<br>
        {{ recipeInfo.recipe_type }}<br> -->


        <!-- For loading ingredients and quantity -->
        
        
        <!-- {% for ri in ingredients %}<br>
        {{ ri.ingredient }} : {{ ri.amount }} {{ ri.ingredient.measurement_scale }} <br>
            
        {% endfor %} -->


        <!-- Comment section -->
        <!-- <form class="box" action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.description }}<br>
        <input class="login" type="submit" name="" value="Comment">
        </form>
    {% endif %}
    {% if message %}
        <div> {{ message }}</div>
    {% endif %} -->
    


{% endblock %}